// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApQeQe0kzlF8WFbvN2XMUkmbAq5Qw6144',
    appId: '1:227894345907:web:d31b2c1cea8ce5e75570c6',
    messagingSenderId: '227894345907',
    projectId: 'apache-riders',
    authDomain: 'apache-riders.firebaseapp.com',
    storageBucket: 'apache-riders.appspot.com',
    measurementId: 'G-8GQTCGZ7L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGS5HMzfrJczwMay_iTTbKPllmfkKPXQw',
    appId: '1:227894345907:android:ddf5e89010b79bee5570c6',
    messagingSenderId: '227894345907',
    projectId: 'apache-riders',
    storageBucket: 'apache-riders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU62OgsZYZXOZYPsx6k7mTwxgD8rZoI-M',
    appId: '1:227894345907:ios:8cf12c6b0ac8e1ea5570c6',
    messagingSenderId: '227894345907',
    projectId: 'apache-riders',
    storageBucket: 'apache-riders.appspot.com',
    iosBundleId: 'com.example.apacheRiders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU62OgsZYZXOZYPsx6k7mTwxgD8rZoI-M',
    appId: '1:227894345907:ios:8cf12c6b0ac8e1ea5570c6',
    messagingSenderId: '227894345907',
    projectId: 'apache-riders',
    storageBucket: 'apache-riders.appspot.com',
    iosBundleId: 'com.example.apacheRiders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApQeQe0kzlF8WFbvN2XMUkmbAq5Qw6144',
    appId: '1:227894345907:web:536131565da361df5570c6',
    messagingSenderId: '227894345907',
    projectId: 'apache-riders',
    authDomain: 'apache-riders.firebaseapp.com',
    storageBucket: 'apache-riders.appspot.com',
    measurementId: 'G-063P5M0L4Z',
  );
}
